### ISSUE TITLE
Typescript compile error happens when calling an action from another action of the same model

### ISSUE THREAD

**Issue by mydearxym** [samuelalvin/react-mobx-mobxstatetree#1]
## context
in typescript project

```js
export const Project = types.model("Project", {
    id: types.number,
    name: types.string,
    isActive: types.optional(types.boolean, false)
})
.views(self => ({
    get root() {
      return getParent(self)
    },
    get  otherRoot() {
      return 'this is ok!' 
   },
    get isLoading(): boolean {
        return  self.root.isLoading
    }
}))
.actions((self) => ({
  ....
}));

```

```js
export const ProjectStore = types.model("ProjectStore", {
    projects: types.array(Project)
})
.views(self => ({
    get isLoading(): boolean {
        return false
    }
}))
.actions((self) => ({
   .....
}));


export type IProject = typeof Project.Type;
export type IProjectStore = typeof ProjectStore.Type;
```

## issue 

when compile with typescript 

``` bash
error TS2339: Property 'root' does not exist on type '{ id: number; name: string; isActive: boolean; } & IStateTreeNode'.
```

seems getParent from mobx-state-tree cause this error

**Comment by samuelalvin** [comment]
@mydearxym Sorry for the late reply, I didn't get any notification on the opened issue.
The error happens on this `return self.root.isLoading` statement.
We can explicitly cast the `self` to the model type (in this case `IProject`).
The code will looks like this:
```
get isLoading(): boolean {
    return (self as IProject).root.isLoading
}
```
Hope this helps.

**Comment by mydearxym** [comment]
sorry @samuelalvin  i have too much subscriptions ...

your solution works thanks!  but i have drop the typescript and back to es6 js in my [boilerplate](https://github.com/mydearxym/mastani)

**Comment by samuelalvin** [comment]
Great boilerplate you have there @mydearxym ! Thanks for sharing the link!
